import fucntionCurrying from './src/vanillaJS/currying';
import letConst from './src/es6/let_const';
import arrowFunction from './src/es6/arrow-function/arrowFunction';
import sum1or2arguments from './src/vanillaJS/sum1or2arguments';
import animationBoxThis from './src/es6/arrow-function/animationBoxThis';
import defaultArguments from './src/es6/arrow-function/defaultArguments';
import notUseArrowFunc from './src/es6/arrow-function/notUseArrowFunc';
import arrowFuncExercises from './src/es6/arrow-function/arrowFuncExercises';
import nestedTemplateStrings from './src/es6/template-strings/nested';
import ternaryOperatorFragments from './src/es6/template-strings/ternaryOperatorFragments';
import taggedTemplate from './src/es6/template-strings/taggedTemplates';

import abbrSentence from './src/es6/template-strings/abbrSentence';
import saniztizeUserInput from './src/es6/template-strings/sanitizeUserInput';
import newStringMethods from './src/es6/stringMethods';
import destructuringBasics from './src/es6/destructuring/basic';
import arraysDestructuring from './src/es6/destructuring/arrays';
import destructuringFunctions from './src/es6/destructuring/functions';
import iterablesLooping from './src/es6/iterablesLooping';
import newArrayMethods from './src/es6/arrays/newArrayMethods';
import findFindIndex from './src/es6/arrays/findFIndIndex';
import someEvery from './src/es6/arrays/someEvery';
import jumpingLetters from './src/es6/spread-and-rest/jumping-letters';
import removeArrayElement from './src/es6/spread-and-rest/removeArrayElement';
import spreadIntoFunction from './src/es6/spread-and-rest/spreadInFunction';
import restParams from './src/es6/spread-and-rest/restParams';
import objectLiterals from './src/es6/object-literals';
import callback from './src/es6/asyncronous/callback';
import addAsync from './src/es6/asyncronous/promise';
import eventBubbling from './src/vanillaJS/event-bubbling';
import bindCallApply from './src/vanillaJS/bind-call-apply';
import prototypeChain from './src/vanillaJS/prototype-chain';
import runner from './src/es6/assync-await/runner';
import promise from './src/es6/promises/promise';
import async from './src/es6/assync-await/async';
import promiseSerialParallel from './src/es6/assync-await/parallel-serial-execution';
import { Milosz, Person } from './src/es6/classes/class';

// sum1or2arguments();
// fucntionCurrying();
// letConst();
// arrowFunction();
// animationBoxThis();
// defaultArguments();
// notUseArrowFunc();
// arrowFuncExercises();
// nestedTemplateStrings();
// ternaryOperatorFragments();
// taggedTemplate();
// abbrSentence();
// saniztizeUserInput();
// newStringMethods();
// arraysDestructuring();
//  destructuringFunctions();
// iterablesLooping();
// newArrayMethods();
// findFindIndex();
// someEvery();
// removeArrayElement();
// spreadIntoFunction();
// restParams();
// objectLiterals();
// callback();
// addAsync( 4)
//   .then((result) => { console.log(result); })
//   .catch((error) => { console.log(error); });
// eventBubbling();
// bindCallApply();
// prototypeChain();
// runner();
// async();
// promiseSerialParallel();
console.log(Milosz.name, Milosz.surname, 'Class');
console.log(Person.introducePerson());
