import fucntionCurrying from './src/vanillaJS/currying';
import letConst from './src/es6/let_const';
import arrowFunction from './src/es6/arrow-function/arrowFunction';
import sum1or2arguments from './src/vanillaJS/sum1or2arguments';
import animationBoxThis from './src/es6/arrow-function/animationBoxThis';
import defaultArguments from './src/es6/arrow-function/defaultArguments';
import notUseArrowFunc from './src/es6/arrow-function/notUseArrowFunc';
import arrowFuncExercises from './src/es6/arrow-function/arrowFuncExercises';
import nestedTemplateStrings from './src/es6/template-strings/nested';
import ternaryOperatorFragments from './src/es6/template-strings/ternaryOperatorFragments';
import taggedTemplate from './src/es6/template-strings/taggedTemplates';

import abbrSentence from './src/es6/template-strings/abbrSentence';
import saniztizeUserInput from './src/es6/template-strings/sanitizeUserInput';
import newStringMethods from './src/es6/stringMethods';
import destructuringBasics from './src/es6/destructuring/basic';
import arraysDestructuring from './src/es6/destructuring/arrays';
import destructuringFunctions from './src/es6/destructuring/functions';

// sum1or2arguments();
// fucntionCurrying();
// letConst();
// arrowFunction();
// animationBoxThis();
// defaultArguments();
// notUseArrowFunc();
// arrowFuncExercises();
// nestedTemplateStrings();
// ternaryOperatorFragments();
// taggedTemplate();
// abbrSentence();
// saniztizeUserInput();
// newStringMethods();
// arraysDestructuring();
destructuringFunctions();
